on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add main.rb
        run: echo 'puts "Hello, World!"' > main.rb

      - name: Run main.rb
        run: ruby main.rb

        
