on:
  push:

env:
  NAME: rubygems-publish
  VERSION: "1.0.${{ github.run_number }}"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          version: 2.6.x

      - name: Add lib/${{ env.NAME }}.rb
        run: |
          mkdir lib
          cat > lib/${{ env.NAME }}.rb << EOM
          def hello
              puts "Hello, World!"
          end
          EOM

      - name: Add ${{ env.NAME }}.gemspec
        run: |
          cat > ${{ env.NAME }}.gemspec << EOM
          Gem::Specification.new do |s|
              s.name        = '${{ env.NAME }}'
              s.version     = '${{ env.VERSION }}'
              s.licenses    = ['MIT']
              s.summary     = "This is an example!"
              s.description = "Much longer explanation of the example!"
              s.authors     = ["Ruby Coder"]
              s.email       = 'rubycoder@example.com'
              s.files       = ["lib/${{ env.NAME }}.rb"]
              s.homepage    = 'https://rubygems.org/gems/example'
              s.metadata    = {
                  "source_code_uri" => "https://github.com/${{ github.repository }}",
                  "github_repo" => "https://github.com/${{ github.repository }}"
              }
          end
          EOM
          
      - name: Create $HOME/.gem/credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${{ github.token }}\n" > $HOME/.gem/credentials

      - name: Build .gem
        run: gem build *.gemspec

      - name: Publish .gem
        run: gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem

      - run: gh api repos/${{ github.repository_owner }}/rubygems-install/dispatches <<< '{"event_type":"build"}' --input -
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
